FROM golang:1.14 as builder

ARG WORKPATH

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -yy gcc bzr jq pkg-config mesa-opencl-icd ocl-icd-opencl-dev

RUN useradd -ms /bin/bash lotus-dev
WORKDIR /home/lotus-dev

USER lotus-dev
