name: Build jobs

on:
  pull_request

jobs:
  build_node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build Lotus Main
        run: |
          export READ_TOKEN=${{ secrets.PECORINO_READ_TOKEN }}
          make build

  build_light_node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build Lotus Main
        run: |
          export READ_TOKEN=${{ secrets.PECORINO_READ_TOKEN }}
          make build_light

  build_devnet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build Lotus Devnet
        run: |
          export READ_TOKEN=${{ secrets.PECORINO_READ_TOKEN }}
          make build_devnet

  build_butterfly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build Lotus Butterfly
        run: |
          export READ_TOKEN=${{ secrets.PECORINO_READ_TOKEN }}
          make build_butterfly

  build_calibration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build Lotus Calibration
        run: |
          export READ_TOKEN=${{ secrets.PECORINO_READ_TOKEN }}
          make build_calibration

  build_wallaby:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build Lotus Wallaby
        run: |
          export READ_TOKEN=${{ secrets.PECORINO_READ_TOKEN }}
          make build_wallaby
